export enum CredentialLifecycleStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  ROTATION_REQUIRED = 'ROTATION_REQUIRED',
  WITHOUT_POLICY = 'WITHOUT_POLICY',
}

export const CREDENTIAL_EXPIRING_SOON_DAYS = 30;
